import { useState } from 'react';
import Navbar from '../../components/navbar';
import 'bootstrap/dist/css/bootstrap.css';
import Head from 'next/head';

function App({ Component, pageProps }) {
  const [autenticado, setAutenticado] = useState(false);
  const [dadosUsuario, setDadosUsuario] = useState({});

  const autenticacao = {isAutenticado: autenticado, autenticar: setAutenticado}
  const dadosUser = {dadosUsuario: dadosUsuario, setDadosUsuario: setDadosUsuario}

  return (
    <>
    <Head>
        <title>Simulado Saeb</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    {autenticado && (
      <Navbar autenticacao={autenticacao}
      dadosUser={dadosUser}/>
    )}
    
        <Component {...pageProps} 
        autenticacao={autenticacao}
        dadosUser={dadosUser} />
    </>
  )
    ;
}

export default App;