import Head from "next/head";
import 'bootstrap/dist/css/bootstrap.css';

export default function Home() {
  return (
    <>
      <Head>
        <title>Simulado Saeb</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
}
